/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConstantChargeType } from '../models/ConstantChargeType';
import { HttpFile } from '../http/http';

export class AIProject {
    'symbol': string;
    'logo'?: string;
    'name': string;
    'url'?: string;
    'description'?: string;
    'tags'?: Array<string>;
    'chargeType': ConstantChargeType;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "symbol",
            "baseName": "symbol",
            "type": "string",
            "format": ""
        },
        {
            "name": "logo",
            "baseName": "logo",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "chargeType",
            "baseName": "chargeType",
            "type": "ConstantChargeType",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AIProject.attributeTypeMap;
    }

    public constructor() {
    }
}



