/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AIArticle } from '../models/AIArticle';
import { AIProject } from '../models/AIProject';
import { AIPrompt } from '../models/AIPrompt';
import { HttpFile } from '../http/http';

export class AiSearchResult {
    'projects'?: Array<AIProject>;
    'prompts'?: Array<AIPrompt>;
    'article'?: Array<AIArticle>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "projects",
            "baseName": "projects",
            "type": "Array<AIProject>",
            "format": ""
        },
        {
            "name": "prompts",
            "baseName": "prompts",
            "type": "Array<AIPrompt>",
            "format": ""
        },
        {
            "name": "article",
            "baseName": "article",
            "type": "Array<AIArticle>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AiSearchResult.attributeTypeMap;
    }

    public constructor() {
    }
}

