/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export type ConstantAppointmentStatus = "CREATE" | "REQ_CANCEL_BY_USER" | "FILLED" | "PAID" | "NEED_CONFIRM" | "CONFIRMED_AT_LEAST_ONE" | "START" | "NOT_EMPTY" | "FINISHED" | "CANCELED" ;
