/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BucketImage } from '../models/BucketImage';
import { ConstantFillType } from '../models/ConstantFillType';
import { HttpFile } from '../http/http';

export class FillInItemValue {
    'name': string;
    'label': string;
    'description': string;
    'required': boolean;
    'inputType': ConstantFillType;
    'order': number;
    'text'?: string;
    'images'?: Array<BucketImage>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "required",
            "baseName": "required",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "inputType",
            "baseName": "inputType",
            "type": "ConstantFillType",
            "format": ""
        },
        {
            "name": "order",
            "baseName": "order",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string",
            "format": ""
        },
        {
            "name": "images",
            "baseName": "images",
            "type": "Array<BucketImage>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FillInItemValue.attributeTypeMap;
    }

    public constructor() {
    }
}



