/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConstantMSG } from '../models/ConstantMSG';
import { YuelemeAppointment } from '../models/YuelemeAppointment';
import { HttpFile } from '../http/http';

export class NoSqlPagingListDataYuelemeAppointment {
    'code': ConstantMSG;
    'msg': string;
    'records'?: Array<YuelemeAppointment>;
    'pageSize': number;
    'pageState'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "ConstantMSG",
            "format": ""
        },
        {
            "name": "msg",
            "baseName": "msg",
            "type": "string",
            "format": ""
        },
        {
            "name": "records",
            "baseName": "records",
            "type": "Array<YuelemeAppointment>",
            "format": ""
        },
        {
            "name": "pageSize",
            "baseName": "pageSize",
            "type": "number",
            "format": ""
        },
        {
            "name": "pageState",
            "baseName": "pageState",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return NoSqlPagingListDataYuelemeAppointment.attributeTypeMap;
    }

    public constructor() {
    }
}



