/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ReqCreateSchedule {
    'name': string;
    'isDefault': boolean;
    'd1Disabled': boolean;
    'd2Disabled': boolean;
    'd3Disabled': boolean;
    'd4Disabled': boolean;
    'd5Disabled': boolean;
    'd6Disabled': boolean;
    'd7Disabled': boolean;
    'disableHoliday'?: boolean;
    'disableWorkDay'?: boolean;
    'd1Start'?: string;
    'd1End'?: string;
    'd2Start'?: string;
    'd2End'?: string;
    'd3Start'?: string;
    'd3End'?: string;
    'd4Start'?: string;
    'd4End'?: string;
    'd5Start'?: string;
    'd5End'?: string;
    'd6Start'?: string;
    'd6End'?: string;
    'd7Start'?: string;
    'd7End'?: string;
    'blackDays'?: Array<string>;
    'seq': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "isDefault",
            "baseName": "isDefault",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "d1Disabled",
            "baseName": "d1Disabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "d2Disabled",
            "baseName": "d2Disabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "d3Disabled",
            "baseName": "d3Disabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "d4Disabled",
            "baseName": "d4Disabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "d5Disabled",
            "baseName": "d5Disabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "d6Disabled",
            "baseName": "d6Disabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "d7Disabled",
            "baseName": "d7Disabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "disableHoliday",
            "baseName": "disableHoliday",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "disableWorkDay",
            "baseName": "disableWorkDay",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "d1Start",
            "baseName": "d1Start",
            "type": "string",
            "format": ""
        },
        {
            "name": "d1End",
            "baseName": "d1End",
            "type": "string",
            "format": ""
        },
        {
            "name": "d2Start",
            "baseName": "d2Start",
            "type": "string",
            "format": ""
        },
        {
            "name": "d2End",
            "baseName": "d2End",
            "type": "string",
            "format": ""
        },
        {
            "name": "d3Start",
            "baseName": "d3Start",
            "type": "string",
            "format": ""
        },
        {
            "name": "d3End",
            "baseName": "d3End",
            "type": "string",
            "format": ""
        },
        {
            "name": "d4Start",
            "baseName": "d4Start",
            "type": "string",
            "format": ""
        },
        {
            "name": "d4End",
            "baseName": "d4End",
            "type": "string",
            "format": ""
        },
        {
            "name": "d5Start",
            "baseName": "d5Start",
            "type": "string",
            "format": ""
        },
        {
            "name": "d5End",
            "baseName": "d5End",
            "type": "string",
            "format": ""
        },
        {
            "name": "d6Start",
            "baseName": "d6Start",
            "type": "string",
            "format": ""
        },
        {
            "name": "d6End",
            "baseName": "d6End",
            "type": "string",
            "format": ""
        },
        {
            "name": "d7Start",
            "baseName": "d7Start",
            "type": "string",
            "format": ""
        },
        {
            "name": "d7End",
            "baseName": "d7End",
            "type": "string",
            "format": ""
        },
        {
            "name": "blackDays",
            "baseName": "blackDays",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "seq",
            "baseName": "seq",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ReqCreateSchedule.attributeTypeMap;
    }

    public constructor() {
    }
}

