/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppointmentEventLog } from '../models/AppointmentEventLog';
import { ConstantAppointmentAction } from '../models/ConstantAppointmentAction';
import { DeliveryContent } from '../models/DeliveryContent';
import { FillInItemValue } from '../models/FillInItemValue';
import { HttpFile } from '../http/http';

export class ReqChange2Appointment {
    'id': number;
    'fromTime'?: number;
    'status': ConstantAppointmentAction;
    'note'?: string;
    'fillInItem'?: Array<FillInItemValue>;
    'deliveryContent'?: DeliveryContent;
    'history'?: Array<AppointmentEventLog>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "fromTime",
            "baseName": "fromTime",
            "type": "number",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "ConstantAppointmentAction",
            "format": ""
        },
        {
            "name": "note",
            "baseName": "note",
            "type": "string",
            "format": ""
        },
        {
            "name": "fillInItem",
            "baseName": "fillInItem",
            "type": "Array<FillInItemValue>",
            "format": ""
        },
        {
            "name": "deliveryContent",
            "baseName": "deliveryContent",
            "type": "DeliveryContent",
            "format": ""
        },
        {
            "name": "history",
            "baseName": "history",
            "type": "Array<AppointmentEventLog>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ReqChange2Appointment.attributeTypeMap;
    }

    public constructor() {
    }
}



