/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ReqChangeAppointment {
    'isCancel': number;
    'msg'?: string;
    'appointmentId': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "isCancel",
            "baseName": "isCancel",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "msg",
            "baseName": "msg",
            "type": "string",
            "format": ""
        },
        {
            "name": "appointmentId",
            "baseName": "appointmentId",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return ReqChangeAppointment.attributeTypeMap;
    }

    public constructor() {
    }
}

