/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ReqGetServiceTime {
    'serviceId': number;
    'startTime': number;
    'endTime': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "serviceId",
            "baseName": "serviceId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "startTime",
            "baseName": "startTime",
            "type": "number",
            "format": ""
        },
        {
            "name": "endTime",
            "baseName": "endTime",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ReqGetServiceTime.attributeTypeMap;
    }

    public constructor() {
    }
}

