/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BucketImage } from '../models/BucketImage';
import { RichFragement } from '../models/RichFragement';
import { HttpFile } from '../http/http';

export class ReqPatchAddress {
    'id': number;
    'name'?: string;
    'lng'?: number;
    'lat'?: number;
    'images'?: Array<BucketImage>;
    'description'?: RichFragement;
    'guideTips'?: RichFragement;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "lng",
            "baseName": "lng",
            "type": "number",
            "format": "double"
        },
        {
            "name": "lat",
            "baseName": "lat",
            "type": "number",
            "format": "double"
        },
        {
            "name": "images",
            "baseName": "images",
            "type": "Array<BucketImage>",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "RichFragement",
            "format": ""
        },
        {
            "name": "guideTips",
            "baseName": "guideTips",
            "type": "RichFragement",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ReqPatchAddress.attributeTypeMap;
    }

    public constructor() {
    }
}

