/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BucketImage } from '../models/BucketImage';
import { ConstantChargeType } from '../models/ConstantChargeType';
import { ConstantDeliveryType } from '../models/ConstantDeliveryType';
import { ConstantOnSelfStatus } from '../models/ConstantOnSelfStatus';
import { FillInItem } from '../models/FillInItem';
import { RichFragement } from '../models/RichFragement';
import { HttpFile } from '../http/http';

export class ReqPatchServiceCardItem {
    'id': number;
    'onShelfStatus'?: ConstantOnSelfStatus;
    'duration'?: string;
    'deliveryType'?: ConstantDeliveryType;
    'urlName'?: string;
    'name'?: string;
    'needConfirmed'?: boolean;
    'faq'?: string;
    'locationNeeded'?: boolean;
    'scheduleId'?: number;
    'locationId'?: number;
    'onLineEnabled'?: boolean;
    'onLinePlatform'?: string;
    'avatar'?: BucketImage;
    'images'?: Array<BucketImage>;
    'description'?: RichFragement;
    'scheduledMsgAfterAppointment'?: string;
    'limitedFutureBookingDays'?: number;
    'limitedBookFrequency'?: number;
    'chargeType': ConstantChargeType;
    'price'?: number;
    'fillInList'?: Array<FillInItem>;
    'refundTimeLimit'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "onShelfStatus",
            "baseName": "onShelfStatus",
            "type": "ConstantOnSelfStatus",
            "format": ""
        },
        {
            "name": "duration",
            "baseName": "duration",
            "type": "string",
            "format": ""
        },
        {
            "name": "deliveryType",
            "baseName": "deliveryType",
            "type": "ConstantDeliveryType",
            "format": ""
        },
        {
            "name": "urlName",
            "baseName": "urlName",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "needConfirmed",
            "baseName": "needConfirmed",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "faq",
            "baseName": "faq",
            "type": "string",
            "format": ""
        },
        {
            "name": "locationNeeded",
            "baseName": "locationNeeded",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "scheduleId",
            "baseName": "scheduleId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "locationId",
            "baseName": "locationId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "onLineEnabled",
            "baseName": "onLineEnabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "onLinePlatform",
            "baseName": "onLinePlatform",
            "type": "string",
            "format": ""
        },
        {
            "name": "avatar",
            "baseName": "avatar",
            "type": "BucketImage",
            "format": ""
        },
        {
            "name": "images",
            "baseName": "images",
            "type": "Array<BucketImage>",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "RichFragement",
            "format": ""
        },
        {
            "name": "scheduledMsgAfterAppointment",
            "baseName": "scheduledMsgAfterAppointment",
            "type": "string",
            "format": ""
        },
        {
            "name": "limitedFutureBookingDays",
            "baseName": "limitedFutureBookingDays",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "limitedBookFrequency",
            "baseName": "limitedBookFrequency",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "chargeType",
            "baseName": "chargeType",
            "type": "ConstantChargeType",
            "format": ""
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number",
            "format": "double"
        },
        {
            "name": "fillInList",
            "baseName": "fillInList",
            "type": "Array<FillInItem>",
            "format": ""
        },
        {
            "name": "refundTimeLimit",
            "baseName": "refundTimeLimit",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return ReqPatchServiceCardItem.attributeTypeMap;
    }

    public constructor() {
    }
}



