/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ReqQuickAppointmentShare {
    'title': string;
    'date': number;
    'remark'?: string;
    'money'?: number;
    'duration': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "date",
            "baseName": "date",
            "type": "number",
            "format": ""
        },
        {
            "name": "remark",
            "baseName": "remark",
            "type": "string",
            "format": ""
        },
        {
            "name": "money",
            "baseName": "money",
            "type": "number",
            "format": "double"
        },
        {
            "name": "duration",
            "baseName": "duration",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ReqQuickAppointmentShare.attributeTypeMap;
    }

    public constructor() {
    }
}

