/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppointmentTime } from '../models/AppointmentTime';
import { StartEndTime } from '../models/StartEndTime';
import { HttpFile } from '../http/http';

export class StartEndTimeItem {
    'date': number;
    'avaiable': boolean;
    'startEnd'?: StartEndTime;
    'unTime'?: Array<AppointmentTime>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "date",
            "baseName": "date",
            "type": "number",
            "format": ""
        },
        {
            "name": "avaiable",
            "baseName": "avaiable",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "startEnd",
            "baseName": "startEnd",
            "type": "StartEndTime",
            "format": ""
        },
        {
            "name": "unTime",
            "baseName": "unTime",
            "type": "Array<AppointmentTime>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StartEndTimeItem.attributeTypeMap;
    }

    public constructor() {
    }
}

