/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConstantAppointmentStatus } from '../models/ConstantAppointmentStatus';
import { ConstantOrganizerRole } from '../models/ConstantOrganizerRole';
import { ConstantYuelemeScheduleStatus } from '../models/ConstantYuelemeScheduleStatus';
import { HttpFile } from '../http/http';

export class UserCalendarRecord {
    'id': number;
    'userId': string;
    'startTime': number;
    'endTime': number;
    'role': ConstantOrganizerRole;
    'duration': string;
    'title': string;
    'appointmentId': number;
    'appointmentStatus': ConstantAppointmentStatus;
    'scheduleStatus': ConstantYuelemeScheduleStatus;
    'memberCount': number;
    'participantUsers'?: Array<string>;
    'remark'?: string;
    'obsoleted': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "startTime",
            "baseName": "startTime",
            "type": "number",
            "format": ""
        },
        {
            "name": "endTime",
            "baseName": "endTime",
            "type": "number",
            "format": ""
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "ConstantOrganizerRole",
            "format": ""
        },
        {
            "name": "duration",
            "baseName": "duration",
            "type": "string",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "appointmentId",
            "baseName": "appointmentId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "appointmentStatus",
            "baseName": "appointmentStatus",
            "type": "ConstantAppointmentStatus",
            "format": ""
        },
        {
            "name": "scheduleStatus",
            "baseName": "scheduleStatus",
            "type": "ConstantYuelemeScheduleStatus",
            "format": ""
        },
        {
            "name": "memberCount",
            "baseName": "memberCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "participantUsers",
            "baseName": "participantUsers",
            "type": "Array<string>",
            "format": "uuid"
        },
        {
            "name": "remark",
            "baseName": "remark",
            "type": "string",
            "format": ""
        },
        {
            "name": "obsoleted",
            "baseName": "obsoleted",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UserCalendarRecord.attributeTypeMap;
    }

    public constructor() {
    }
}



