/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class WechatPaymentItem {
    'timeStamp': number;
    'appId': string;
    'nonceStr': string;
    '_package': string;
    'paySign': string;
    'signType': string;
    'orderId': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "timeStamp",
            "baseName": "timeStamp",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "appId",
            "baseName": "appId",
            "type": "string",
            "format": ""
        },
        {
            "name": "nonceStr",
            "baseName": "nonceStr",
            "type": "string",
            "format": ""
        },
        {
            "name": "_package",
            "baseName": "package",
            "type": "string",
            "format": ""
        },
        {
            "name": "paySign",
            "baseName": "paySign",
            "type": "string",
            "format": ""
        },
        {
            "name": "signType",
            "baseName": "signType",
            "type": "string",
            "format": ""
        },
        {
            "name": "orderId",
            "baseName": "orderId",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WechatPaymentItem.attributeTypeMap;
    }

    public constructor() {
    }
}

