/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConstantGetMoneyType } from '../models/ConstantGetMoneyType';
import { ConstantWithdrawStatus1 } from '../models/ConstantWithdrawStatus1';
import { HttpFile } from '../http/http';

export class WithdrawApplicaton {
    'channelId': number;
    'id': number;
    'userId': string;
    'createAt': number;
    'withdrawStatus': ConstantWithdrawStatus1;
    'withdrawCharge': number;
    'wechatOpenId'?: string;
    'getMoneyType': ConstantGetMoneyType;
    'bankCode'?: string;
    'bankCardId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "channelId",
            "baseName": "channelId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "createAt",
            "baseName": "createAt",
            "type": "number",
            "format": ""
        },
        {
            "name": "withdrawStatus",
            "baseName": "withdrawStatus",
            "type": "ConstantWithdrawStatus1",
            "format": ""
        },
        {
            "name": "withdrawCharge",
            "baseName": "withdrawCharge",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "wechatOpenId",
            "baseName": "wechatOpenId",
            "type": "string",
            "format": ""
        },
        {
            "name": "getMoneyType",
            "baseName": "getMoneyType",
            "type": "ConstantGetMoneyType",
            "format": ""
        },
        {
            "name": "bankCode",
            "baseName": "bankCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "bankCardId",
            "baseName": "bankCardId",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WithdrawApplicaton.attributeTypeMap;
    }

    public constructor() {
    }
}



