/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppointmentEventLog } from '../models/AppointmentEventLog';
import { ConstantAppointmentStatus } from '../models/ConstantAppointmentStatus';
import { DeliveryContent } from '../models/DeliveryContent';
import { FillInItemValue } from '../models/FillInItemValue';
import { HttpFile } from '../http/http';

export class YuelemeAppointment {
    'id': number;
    'userId': string;
    'tutorId': string;
    'serviceCardId': number;
    'fromTime': number;
    'note'?: string;
    'fillInItem'?: Array<FillInItemValue>;
    'status': ConstantAppointmentStatus;
    'deliveryContent'?: DeliveryContent;
    'history'?: Array<AppointmentEventLog>;
    'statusInfo'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "tutorId",
            "baseName": "tutorId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "serviceCardId",
            "baseName": "serviceCardId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "fromTime",
            "baseName": "fromTime",
            "type": "number",
            "format": ""
        },
        {
            "name": "note",
            "baseName": "note",
            "type": "string",
            "format": ""
        },
        {
            "name": "fillInItem",
            "baseName": "fillInItem",
            "type": "Array<FillInItemValue>",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "ConstantAppointmentStatus",
            "format": ""
        },
        {
            "name": "deliveryContent",
            "baseName": "deliveryContent",
            "type": "DeliveryContent",
            "format": ""
        },
        {
            "name": "history",
            "baseName": "history",
            "type": "Array<AppointmentEventLog>",
            "format": ""
        },
        {
            "name": "statusInfo",
            "baseName": "statusInfo",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return YuelemeAppointment.attributeTypeMap;
    }

    public constructor() {
    }
}



