import Head from "next/head";
import {useRouter} from "next/router";
import React, {FC} from "react";

import dynamic from 'next/dynamic'
import NoSsrPosts from '../../components/load';
import {useParams} from "next/navigation";

const A = dynamic(() => Promise.resolve(NoSsrPosts), {
    ssr: false
})


export default function Tags() {
    const router = useRouter()
    const p = useParams();
    const tag = p?.tag ?? 'AI'
    return (
        <>
            <Head>
                <title>今日最AI</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {/*@ts-ignore*/}
<A tag={tag ?? 'AI'}>
</A>

        </>
    );
}
