import Head from "next/head";
import React, { FC } from "react";

import dynamic from "next/dynamic";
import NoSsrPosts from "../../components/load";
import { useParams } from "next/navigation";
import { useSearchParams } from "next/dist/client/components/navigation";

const A = dynamic(() => Promise.resolve(NoSsrPosts), {
  ssr: false,
});

export default function Tags() {
  const p = useSearchParams();
  const tag = p?.get("tag") ?? "AI";
  return (
    <>
      <Head>
        <title>今日最AI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/*@ts-ignore*/}
      <A tag={tag ?? "AI"}></A>
    </>
  );
}
