import { Anchor, Button, Stack, Text } from "@mantine/core";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Next + Mantine + TypeScript</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Stack align="center">
        <Text>Mantine UI is so Cool</Text>

        <Anchor href="https://github.com/U-C-S/nextjs-mantine-typescript-template">
          <Button variant="outline">GitHub</Button>
        </Anchor>
      </Stack>
    </>
  );
}
