import { Anchor, Button, Stack, Text } from "@mantine/core";
import Head from "next/head";
import { Posts } from "../../components/post";
import {useRouter} from "next/router";

export default function Home() {
    const router = useRouter()
    const tag = Array.isArray(router.query.tag) ? router.query.tag[0]: router.query.tag
    return (
        <>
            <Head>
                <title>今日最AI</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Posts key={tag} tag={tag ?? 'AI'}></Posts>
        </>
    );
}
