name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --build-arg NEXT_PUBLIC_BACKEND_API=${{secrets.NEXT_PUBLIC_BACKEND_API}} --build-arg AUTH0_SECRET=${{secrets.AUTH0_SECRET}} --build-arg AUTH0_BASE_URL=${{secrets.AUTH0_BASE_URL}}  --build-arg AUTH0_ISSUER_BASE_URL=${{secrets.AUTH0_ISSUER_BASE_URL}}  --build-arg AUTH0_CLIENT_ID=${{secrets.AUTH0_CLIENT_ID}}  --build-arg AUTH0_CLIENT_SECRET=${{secrets.AUTH0_CLIENT_SECRET}} . --file Dockerfile --tag zuijintoday:$(date +%s)

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: rang:zuijintoday:latest
