name: Docker Image CI

on:
  push:
    branches: [ "develop", "feature/ci"]
  pull_request:
    branches: [ "develop", "feature/ci" ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: DOCKERHUB_USERNAME
    steps:
    - name: Build the Docker image
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{secrets.DOCKER_REGISTRY}}/rang/zuijintoday
        tags: |
          type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'develop') }}
          type=schedule
          type=sha

    - name: Log details
      env: # Or as an environment variable
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        NEXT_PUBLIC_BACKEND_API: ${{ secrets.NEXT_PUBLIC_BACKEND_API }}
      run: |
          echo "NEXT_PUBLIC_BACKEND_API: ${{ env.NEXT_PUBLIC_BACKEND_API }}"
          echo "PUBLIC_BACKEND_API: ${{ env.PUBLIC_BACKEND_API }}"
          echo "DEPLOY_TARGETS: ${{ env.DEPLOY_TARGETS }}"

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      env: # Or as an environment variable
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        NEXT_PUBLIC_BACKEND_API: ${{ secrets.NEXT_PUBLIC_BACKEND_API }}
      with:
        context: .
        push: true
        build-args:
          DOCKERHUB_USERNAME=${{secrets.DOCKERHUB_USERNAME}}
          DOCKERHUB_TOKEN=${{secrets.DOCKERHUB_TOKEN}}
          DOCKER_REGISTRY=${{secrets.DOCKER_REGISTRY}}
          NEXT_PUBLIC_BACKEND_API=${{ secrets.NEXT_PUBLIC_BACKEND_API }}
          PUBLIC_BACKEND_API=${{ secrets.PUBLIC_BACKEND_API }}
          AUTH0_SECRET=${{ secrets.AUTH0_SECRET }}
          AUTH0_BASE_URL=${{ secrets.AUTH0_BASE_URL }}
          AUTH0_ISSUER_BASE_URL=${{ secrets.AUTH0_ISSUER_BASE_URL }}
          AUTH0_CLIENT_ID=${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_CLIENT_SECRET=${{ secrets.AUTH0_CLIENT_SECRET }}
        tags: ${{ steps.meta.outputs.tags }}
